- id: clang-format-10
  name: clang-format-10
  description: Clang-formatter for my repos, use with .clang-format file
  entry: clang-format-10
  args: ["-style=file -i"]
  language: system
  types: [file]
  files: \.(c|cc|cpp|hpp|h)$
